name: CI/CD Pipeline

on:
  push:
    branches: [ main, Develop ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build dockeractor image
      uses: docker/build-push-action@v2
      with:
        context: ./Security_Bots/Docker-BadActor/
        file: ./Security_Bots/Docker-BadActor/Dockerfile
        load: true

    - name: Build basictrustbot image
      uses: docker/build-push-action@v2
      with:
        context: ./Security_Bots/Docker-BadActor/
        file: ./Security_Bots/TheBasicBot/Dockerfile
        load: true

    - name: Build dockerindocker image
      uses: docker/build-push-action@v2
      with:
        context: ./Security_Bots/Docker-BadActor/
        file: ./Security_Bots/Docker-in-Docker/Dockerfile
        load: true
