name: Weekly Workflow

on:
  schedule:
    - cron: '0 9 * * 1' # Runs at 9:00 AM UTC every Monday

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run SonarScanner
        uses: SonarSource/sonarcloud-github-action@v2.2.0
        with:
            # Additional arguments to the sonar-scanner
            # args: # optional
            # Set the sonar.projectBaseDir analysis property
            projectBaseDir: . # optional, default is .

      - name: Run Python Tests
        run: |
          pytest tests # Adjust the test command as needed

      - name: Check Kubernetes Setup
        run: |
          # Use kubectl commands to validate your Kubernetes setup in the 'k8s' folder
          # For example:
          kubectl get pods -n my-namespace
          # Add other relevant checks

